import json
import re
import os
import matplotlib.pyplot as plt
from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('helvetica', 'B', 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, 'Healium Analysis Report', 0, 0, 'L')
            self.set_x(-30)
            self.cell(20, 10, f'Page {self.page_no()}', 0, 1, 'R')
            self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Generated by Healium Agentic System - Professional Edition', 0, 0, 'C')

def generate_pie_chart(data, output_path='category_dist.png'):
    if not data: return None
    try:
        plt.figure(figsize=(6, 4))
        plt.pie(data.values(), labels=data.keys(), autopct='%1.1f%%', startangle=140, colors=plt.cm.Pastel1.colors)
        plt.title('Error Distribution by Category')
        plt.axis('equal')
        plt.tight_layout()
        plt.savefig(output_path)
        plt.close()
        return output_path
    except Exception as e:
        print(f"Error generating pie chart: {e}")
        return None

def generate_bar_chart(data, output_path='severity_dist.png'):
    if not data: return None
    try:
        order = ["Critical", "Major", "Minor"]
        sorted_keys = [k for k in order if k in data] + [k for k in data if k not in order]
        values = [data[k] for k in sorted_keys]
        
        colors = []
        for k in sorted_keys:
            if k == "Critical": colors.append('#e63946')
            elif k == "Major": colors.append('#f4a261')
            else: colors.append('#2a9d8f')
            
        plt.figure(figsize=(6, 4))
        plt.bar(sorted_keys, values, color=colors)
        plt.title('Errors by Severity')
        plt.ylabel('Count')
        plt.tight_layout()
        plt.savefig(output_path)
        plt.close()
        return output_path
    except Exception as e:
        print(f"Error generating bar chart: {e}")
        return None

def parse_metadata(markdown_content):
    json_match = re.search(r'```json\s*(\{.*?\})\s*```', markdown_content, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group(1))
        except json.JSONDecodeError:
            print("Error: Could not decode JSON metadata.")
    return None

def create_pdf_report(markdown_content, output_filename='healium_analysis_report.pdf'):
    metadata = parse_metadata(markdown_content)
    if not metadata:
        metadata = {
            "total_errors": 0,
            "estimated_fix_time": "Unknown",
            "health_score": 0,
            "technical_debt": "Unknown",
            "error_distribution": {},
            "severity_distribution": {}
        }

    # Generate graphs
    pie_path = generate_pie_chart(metadata.get("error_distribution"))
    bar_path = generate_bar_chart(metadata.get("severity_distribution"))

    pdf = PDFReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # COVER PAGE
    pdf.add_page()
    pdf.set_y(80)
    pdf.set_font('helvetica', 'B', 36)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 20, 'Healium', 0, 1, 'C')
    pdf.set_font('helvetica', 'B', 18)
    pdf.set_text_color(127, 140, 141)
    pdf.cell(0, 10, 'Codebase Intelligence & Analysis Report', 0, 1, 'C')
    
    pdf.set_y(150)
    pdf.set_font('helvetica', '', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f'Total Errors Found: {metadata.get("total_errors")}', 0, 1, 'C')
    pdf.cell(0, 10, f'Project Health Score: {metadata.get("health_score")}/100', 0, 1, 'C')
    pdf.cell(0, 10, f'Technical Debt: {metadata.get("technical_debt")}', 0, 1, 'C')

    # DASHBOARD PAGE
    pdf.add_page()
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 15, 'Executive Dashboard', 0, 1)
    pdf.ln(5)
    
    # Summary Metrics Table
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(60, 10, 'Metric', 1, 0, 'C', True)
    pdf.cell(130, 10, 'Value', 1, 1, 'C', True)
    
    pdf.set_font('helvetica', '', 11)
    metrics = [
        ("Total Issues Found", str(metadata.get("total_errors"))),
        ("Estimated Fix Time", metadata.get("estimated_fix_time")),
        ("Project Health Score", f"{metadata.get('health_score')}/100"),
        ("Technical Debt Level", str(metadata.get("technical_debt")))
    ]
    for label, val in metrics:
        pdf.cell(60, 10, label, 1, 0, 'L')
        pdf.cell(130, 10, val, 1, 1, 'L')
    
    pdf.ln(10)
    
    # Graphs
    curr_y = pdf.get_y()
    if pie_path and os.path.exists(pie_path):
        pdf.image(pie_path, x=10, y=curr_y, w=90)
    if bar_path and os.path.exists(bar_path):
        pdf.image(bar_path, x=105, y=curr_y, w=90)
    
    if pie_path or bar_path:
        pdf.set_y(curr_y + 70)
    
    pdf.ln(10)

    # DETAILS PAGE
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 15, 'Detailed Technical Findings', 0, 1)
    pdf.ln(5)
    
    # Clean content
    display_content = re.sub(r'```json\s*\{.*?\}\s*```', '', markdown_content, flags=re.DOTALL)
    display_content = display_content.replace('REPORT_METADATA', '')
    
    lines = display_content.split('\n')
    for line in lines:
        line = line.strip()
        if not line: 
            pdf.ln(2)
            continue
        
        # Reset X to margin to avoid "Not enough horizontal space" errors
        pdf.set_x(10) 
        
        if line.startswith('# '):
            pdf.ln(5)
            pdf.set_font('helvetica', 'B', 14)
            pdf.set_text_color(44, 62, 80)
            pdf.multi_cell(0, 10, line.strip('# '))
        elif line.startswith('## '):
            pdf.ln(2)
            pdf.set_font('helvetica', 'B', 12)
            pdf.set_text_color(52, 73, 94)
            pdf.multi_cell(0, 8, line.strip('## '))
        elif line.startswith('### '):
            pdf.set_font('helvetica', 'B', 11)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 7, line.strip('### '))
        elif line.startswith('- '):
            pdf.set_font('helvetica', '', 10)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 6, '  ' + line)
        elif line.startswith('```'):
            continue # Skip code markers
        else:
            pdf.set_font('helvetica', '', 10)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 6, line)

    # Cleanup
    try:
        pdf.output(output_filename)
        print(f"Professional PDF report generated: {output_filename}")
    except Exception as e:
        print(f"Error saving PDF: {e}")
        
    if pie_path and os.path.exists(pie_path): os.remove(pie_path)
    if bar_path and os.path.exists(bar_path): os.remove(bar_path)

if __name__ == "__main__":
    test_md = """
# Project Analysis
This is a sample analysis report.

## Issue 1: Missing Variable
- Severity: Critical
- File: main.py
Explanation: The variable is not defined.

REPORT_METADATA
```json
{
  "total_errors": 12,
  "estimated_fix_time": "4.5 hours",
  "health_score": 62,
  "technical_debt": "High",
  "error_distribution": {
    "Logic": 5,
    "Syntax": 4,
    "Security": 3
  },
  "severity_distribution": {
    "Critical": 3,
    "Major": 5,
    "Minor": 4
  }
}
```
"""
    create_pdf_report(test_md, 'test_professional_report.pdf')
